version: "3.8"

volumes:
  db:
  elastic:
services:
  web:
    image: nginx:1.23.2
    ports:
      - "$WEB_PORT:8080"
    volumes:
      - ./:/app-mount
      - ./.dev/nginx/site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php
      - mysql
  php:
    image: drupal/php:8.1.12
    volumes:
      - ./:/app-mount
    working_dir: /app-mount/public
  mysql:
    image: mariadb:10.9.4
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=drupal
    volumes:
      - db:/var/lib/mysql
  elasticsearch:
    image: elasticsearch:8.5.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "$ELASTICSEARCH_PORT:9200"
    volumes:
      - elastic:/usr/share/elasticsearch/data
