version: "3.8"

volumes:
  drupal_db:
services:
  nginx:
    image: nginx:1.23.2
    ports:
      - "$NGINX_PORT:8080"
    volumes:
      - ./:/app-mount
      - ./dev/nginx/site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php
      - mysql
  php:
    image: rig/php:8.1.12
    volumes:
      - ./:/app-mount
  mysql:
    image: mariadb:10.9.4
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=drupal
    volumes:
      - drupal_db:/var/lib/mysql
  elasticsearch:
    image: elasticsearch:8.5.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
